### ISSUE TITLE
【参考】「新增」：BunDragon

### ISSUE THREAD

**Issue by fenychn0206** [fenychn0206/friends#2]
### 交换友链检查清单

- [X] 已经阅读 `README.md`
- [X] 您的站点类型为 `博客`
- [X] [网站域名符合规定](https://github.com/FrederickAsYou/friends/tree/main?tab=readme-ov-file#%E4%BA%A4%E6%8D%A2%E5%89%8D%E8%AF%B7%E9%98%85%E8%AF%BB)
- [X] 网站内容符合国家规定

### 友链信息

```yaml
{
    title: 'BunDragon'
    description: 'just do it.'
    link: 'https://www.setbun.com'
    avatar: 'https://cdn.jsdelivr.net/gh/FrederickBun/upyun-rhimgcdn@img/upload/202406272229074.png'
}
```

### 站点友链地址

https://www.setbun.com/friends
